name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Flask dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository for deployment
      uses: actions/checkout@v4

    - name: Copy Flask app to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: ".,!env/"
        target: "/var/www/flask_app"

    - name: Restart Flask app on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /var/www/flask_app
          sudo apt update -y
          sudo apt install -y python3 python3-pip
          pip install Flask
          EXISTING_PID=$(lsof -t -i:5000 || true)
          if [ -n "$EXISTING_PID" ]; then
            kill -9 "$EXISTING_PID"
            sleep 2
          fi
          nohup python3 app.py > /dev/null 2>&1 &
